[phases.build]
# Install dependencies and build the Angular app
cmd = "npm ci && npm run build -- --prod"

[phases.start]
# Serve the Angular app using a static file server
cmd = "npx http-server dist/apps/hello-monorepo-railway -p $PORT"

[static]
# Specify the directory containing the built Angular app
path = "dist/apps/hello-monorepo-railway"